### ISSUE TITLE
log.Fatal of srv.ListenAndServe() prevents graceful shutdown from occuring

### ISSUE THREAD

**Issue by bsukow** [rumyantseva/advent-2017#1]
`srv.Shutdown(context.Background())` causes `srv.ListenAndServe()` to immediately return an `ErrServerClosed`. Since this value is then immedately passed into `log.Fatal`, the program exits immediately rather than waiting for `srv.Shutdown()` to return. Consequently any open requests are likely to be dropped before graceful shutdown can occur.

Reference:
https://golang.org/pkg/net/http/#Server.Shutdown

I was able to reproduce the locally by adding a 10 second sleep to the `/home` endpoint. Without a `log.Fatal` call, the request is eventually fulfilled after the `SIGTERM`, at which point `Shutdown()` returns and `Done` is logged.

**Comment by rumyantseva** [comment]
@bsukow yeah, thank you very much! It wasn't a good idea to put `log.Fatal` there.
Could you take a look: https://github.com/rumyantseva/advent-2017/pull/2/files?

**Comment by rumyantseva** [comment]
Fixed.
